default_provider: azure

providers:
  azure:
    api_base: https://${AZURE_OPENAI_RESOURCE}.openai.azure.com/
    api_key: ${AZURE_OPENAI_API_KEY}
    api_version: 2025-01-01-preview
    deployments:
      gpt4o:
        model: gpt-4.5-preview
        max_tokens: 8192
        temperature: 0.3
      o3mini:
        model: gpt-3.5-turbo
        max_tokens: 4096
        temperature: 0.5
